import Provider from "@/components/Provider";
import "./globals.css";
import { Inter } from "next/font/google";
import Header from "@/components/Header";
import Header2 from "@/components/Header2";
import Footer from "@/components/Footer";
import { MyContext, MyContextProvider } from "@/components/MyContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className=" overflow-x-hidden hidden2">
        <MyContextProvider >
        <Provider>
          <Header2 />
          {children}
          <Footer />
        </Provider>
        </MyContextProvider>
      </body>
    </html>
  );
}
